# Generated by Django 5.1.3 on 2024-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetap', '0002_order_created_at_order_quantity_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('unavailable', 'Недоступен')], default='available', max_length=20),
        ),
    ]
